### ISSUE TITLE
Make “reviewed date” field editable via spreadsheet

### ISSUE THREAD

**Issue by JacobShaeffer** [SolarSPELL-Main/solarspell-dlms#67]

**Comment by saharshgoenka** [comment]
### Adjust "Year Published" Column for Bulk Content Upload

**Description:**
After downloading metadata, the "Year Published" column has to be manually adjusted to remove the full date (month/day/year) and keep only the year for the spreadsheet to be accepted by the DLMS through the "Add Bulk Content" button on the Contents page.

**Expected Fix:**
Adjust the "Year Published" column on the Excel file to keep only the year so that the DLMS accepts the Excel file without manual modifications.
